# ChatService Plugin Yapılandırması
# Bu plugin, Minecraft sunucunuzda AI temelli sohbet özelliği sağlar.

# API Yapılandırması
api:
  # API URL'i - Bu URL'i değiştirmeyin, özel bir gereksinim olmadığı sürece
  url: 'https://ai.kynux.cloud/v1/chat/completions'
  
  key: "sk-c2dfa81d4b950eadba1ce55273e3d96830962fa1502cebdb987d04f4a8b9dd0b"

  # Kullanılacak AI modeli - /ai models komutu ile mevcut modelleri listeleyebilirsiniz
  model: 'grok-3-mini'
  
  # 0 ile 1 arasında bir değer. Yüksek değerler daha yaratıcı ancak daha az tutarlı yanıtlar üretir.
  # Düşük değerler daha tutarlı ancak daha az yaratıcı yanıtlar üretir.
  temperature: 0.7
  
  # Her yanıt için maksimum token sayısı. Bu değer çok yüksekse, API çok uzun yanıtlar üretebilir.
  max_tokens: 1000

# Sohbet Yapılandırması
chat:
  # AI için sistem mesajı - AI'nın nasıl davranacağını tanımlar
  # Uzun sistem promptlar için | işareti kullanılabilir (tüm satırlar aynı girinti seviyesinde olmalıdır)
  system_prompt: |
    Adın Kynuxai ve Sen yardımcı bir asistansın. Minecraft oyuncusuna kısa ve öz yanıtlar ver.
    Oyuncuların sorularını nezaketle yanıtla ve yardımcı olmaya çalış.
    Minecraft oyunu hakkında bilgi ver ve oyunculara öneriler sun.
    Yanıtlarında renk ve biçimlendirme için Minecraft renk kodlarını kullanabilirsin:
    &0: Siyah        &1: Koyu Mavi     &2: Koyu Yeşil     &3: Koyu Camgöbeği
    &4: Koyu Kırmızı &5: Koyu Mor      &6: Altın          &7: Gri
    &8: Koyu Gri     &9: Mavi          &a: Yeşil          &b: Camgöbeği
    &c: Kırmızı      &d: Pembe         &e: Sarı           &f: Beyaz
    &k: Sihirli      &l: Kalın         &m: Üstü Çizili    &n: Altı Çizili
    &o: İtalik       &r: Sıfırla
    
    Örnek: "Bu metin &cKırmızı &aYeşil &erenkler &lve kalın &naltı çizili &oitalik &rkullanıyor."
    
    Uygun yerlerde renkli metinler kullanarak yanıtlarını daha ilgi çekici hale getirebilirsin.
  
  # AI yanıtlarında renk kodlarını kullanmaya izin ver
  allow_color_codes: true
  
  # Sohbet öneki - AI yanıtlarının önüne gelecek metin
  # Renk kodları için &0-&9, &a-&f, &k-&o kullanılabilir
  prefix: '&b[KynuxAi] &r'
  
  # AI yanıtlarının tüm sunucuya gönderilmesi
  broadcast_responses: true
  
  # Sohbet kontrolleri
  chat_trigger:
    # Sohbette "ai <mesaj>" yazarak AI ile konuşma özelliğini açar/kapatır
    enabled: true
    # Sohbette kullanılacak tetikleyici kelime (örn: "ai naber" yazdığınızda çalışır)
    keyword: 'kynuxai'

# İzinler:
# chatservice.ai - /ai komutunu kullanma izni, default olarak tüm oyunculara verilir
# chatservice.admin - yönetici komutlarını kullanma izni (/ai reload, /ai models, /ai clearall)
