name: ChatService
version: '1.0'
main: org.kynuxcloud.chatService.ChatService
api-version: '1.20'
load: STARTUP
authors: [ Kynux ]
website: https://kynux.cloud

commands:
  ai:
    description: Yapay zeka ile sohbet et
    usage: /ai <mesaj>
    permission: chatservice.ai
    
permissions:
  chatservice.ai:
    description: Yapay zeka ile sohbet etme izni
    default: true
