name: AiChat
version: '1.0'
main: org.kynuxcloud.AiChat.AiChat
api-version: '1.16'
load: STARTUP
authors: [ Kynux ]
website: https://kynux.cloud

commands:
  ai:
    description: Yapay zeka ile sohbet et
    usage: /ai <mesaj>
    permission: aichat.ai
    
permissions:
  aichat.ai:
    description: Yapay zeka ile sohbet etme izni
    default: true
